#!/bin/sh

# This script runs sanity checks before pushing to the remote repository.

if [ -n "$SKIP_HOOKS" ]; then
    echo "Skipping git hooks due to SKIP_HOOKS environment variable"
    exit 0
fi

make lint

if [ $? -ne 0 ]; then
    echo "❌ Linting failed. Fix the issues and try again."
    exit 1
fi

make test

if [ $? -ne 0 ]; then
    echo "❌ Tests failed. Fix the issues and try again."
    exit 1
fi

exit 0
